ubee_dev_admin_markdown_documentation:
  path: /admin/markdown-documentation
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '@UbeeDevAdmin/markdown-documentation.html.twig'

ubee_dev_admin_preview_markdown:
  path: /admin/markdown/preview
  defaults: { _controller: UbeeDev\AdminBundle\Controller\PreviewMarkdownController::preview }