khalil1608_admin_markdown_documentation:
  path: /admin/markdown-documentation
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: '@Khalil1608Admin/markdown-documentation.html.twig'

cartesia_admin_preview_markdown:
  path: /admin/markdown/preview
  defaults: { _controller: Khalil1608\AdminBundle\Controller\PreviewMarkdownController::preview }